const NIGHT_DELAY_MS = 3000;
const NIGHT_TO_DAY_DELAY_MS = 3000;
const DAY_TO_NIGHT_DELAY_MS = 6000;
const POST_REVEAL_DELAY_MS = 6000;
const POST_MAYOR_DELAY_MS = 5000;
const POST_ARMOR_DELAY_MS = 10000;
const NIGHT_RESOLVE_DELAY_MS = 6000;
const HUNTER_SHOT_TIMEOUT_MS = 60000;
const MAYOR_SELECTION_TIMEOUT_MS = 60000;
const MAX_VISIBLE_LOGS = 8;
const MAX_PLAYER_NAME_LENGTH = 20;
const MIN_PLAYERS = 5;

export {
  NIGHT_DELAY_MS,
  NIGHT_TO_DAY_DELAY_MS,
  DAY_TO_NIGHT_DELAY_MS,
  POST_REVEAL_DELAY_MS,
  POST_MAYOR_DELAY_MS,
  POST_ARMOR_DELAY_MS,
  NIGHT_RESOLVE_DELAY_MS,
  HUNTER_SHOT_TIMEOUT_MS,
  MAYOR_SELECTION_TIMEOUT_MS,
  MAX_VISIBLE_LOGS,
  MAX_PLAYER_NAME_LENGTH,
  MIN_PLAYERS,
};
