const NIGHT_DELAY_MS = 3000;
const PHASE_DELAY_MS = 3000;
const POST_REVEAL_DELAY_MS = 5000;
const POST_ARMOR_DELAY_MS = 10000;
const NIGHT_RESOLVE_DELAY_MS = 6000;

export {
  NIGHT_DELAY_MS,
  PHASE_DELAY_MS,
  POST_REVEAL_DELAY_MS,
  POST_ARMOR_DELAY_MS,
  NIGHT_RESOLVE_DELAY_MS
};
